version: '3.8'

services:
  # php-fpm
  php:
    build:
      context: .
      dockerfile: ./docker/php/dockerfile
    image: php:74-custom-fpm-alpine
    restart: always
    environment:
      - SET_CONTAINER_TIMEZONE=true
      - CONTAINER_TIMEZONE=Asia/Shanghai
    volumes:
      - ${APP_PATH}:/var/www/html
      - ./config/php-fpm.conf:/usr/local/etc/php-fpm.d/zz-docker.conf
    
  # web
  nginx:
    build:
      context: .
      dockerfile: ./docker/nginx/dockerfile
    image: nginx:1.24-custom-alpine
    restart: always
    volumes:
      - ./config/vhost.conf:/etc/nginx/templates/default.conf.template
      - ./runtime/log/nginx/:/var/log/nginx/
    volumes_from:
      - php
    ports:
      - "3000:80"
    environment:
      - NGINX_HOST=${APP_HOST}

  # redis
  # redis:
  #   image: redis:alpine3.17
  #   restart: always
  #   networks:
  #     - back

networks:
  defaults:
    name: webapp
