version: '3'

services:
  # php-fpm
  php-fpm:
    build:
      context: .
      dockerfile: dockerfile
    image: php:answersystem-fpm-alpine
    restart: always
    networks:
      - back
    environment:
      - SET_CONTAINER_TIMEZONE=true
      - CONTAINER_TIMEZONE=Asia/Shanghai
    volumes:
      - ${APP_PATH}:/var/www/html
      - ./config/php-fpm.conf:/usr/local/etc/php-fpm.d/zz-docker.conf
    
  # web
  nginx:
    image: nginx:1.24-alpine
    restart: always
    volumes:
      - ./config/vhost.conf:/etc/nginx/templates/default.conf.template
      - ./runtime/log/nginx/:/var/log/nginx/
    volumes_from:
      - php-fpm
    ports:
      - "3001:80"
    networks:
      - back
    environment:
      - NGINX_HOST=localhost
      - NGINX_PORT=80
    links:
      - php-fpm

  # redis
  redis:
    image: redis:alpine3.17
    restart: always
    networks:
      - back

networks:
  back:
    driver: bridge
